"""add_rqyl_column_to_margin_trades

Revision ID: 03af93834e28
Revises: 7908c5ebae95
Create Date: 2025-12-25 12:42:03.579860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03af93834e28'
down_revision: Union[str, None] = '7908c5ebae95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('margin_trades', sa.Column('rqyl', sa.BigInteger(), nullable=True, comment='融券余量（股）'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('margin_trades', 'rqyl')
    # ### end Alembic commands ###
