"""add capital flow, sentiment, valuation and tech indicator tables

Revision ID: 7908c5ebae95
Revises: 004
Create Date: 2025-12-25 06:45:15.117705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7908c5ebae95'
down_revision: Union[str, None] = '004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_valuations',
    sa.Column('code', sa.String(length=10), nullable=False, comment='股票代码'),
    sa.Column('trade_date', sa.Date(), nullable=False, comment='交易日期'),
    sa.Column('pe_ttm', sa.Numeric(precision=12, scale=4), nullable=True, comment='市盈率（TTM）'),
    sa.Column('pe_static', sa.Numeric(precision=12, scale=4), nullable=True, comment='市盈率（静态）'),
    sa.Column('pb', sa.Numeric(precision=12, scale=4), nullable=True, comment='市净率'),
    sa.Column('ps_ttm', sa.Numeric(precision=12, scale=4), nullable=True, comment='市销率（TTM）'),
    sa.Column('peg', sa.Numeric(precision=12, scale=4), nullable=True, comment='PEG'),
    sa.Column('total_mv', sa.Numeric(precision=18, scale=2), nullable=True, comment='总市值（亿元）'),
    sa.Column('circ_mv', sa.Numeric(precision=18, scale=2), nullable=True, comment='流通市值（亿元）'),
    sa.Column('dv_ttm', sa.Numeric(precision=8, scale=4), nullable=True, comment='股息率（TTM）（%）'),
    sa.PrimaryKeyConstraint('code', 'trade_date', name=op.f('pk_daily_valuations')),
    comment='每日估值数据表'
    )
    op.create_index('ix_daily_valuations_code', 'daily_valuations', ['code'], unique=False)
    op.create_index('ix_daily_valuations_date', 'daily_valuations', ['trade_date'], unique=False)
    op.create_table('dragon_tiger',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False, comment='股票代码'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='股票名称'),
    sa.Column('trade_date', sa.Date(), nullable=False, comment='交易日期'),
    sa.Column('reason', sa.String(length=200), nullable=False, comment='上榜原因'),
    sa.Column('buy_amount', sa.Numeric(precision=18, scale=2), nullable=True, comment='龙虎榜买入额（万元）'),
    sa.Column('sell_amount', sa.Numeric(precision=18, scale=2), nullable=True, comment='龙虎榜卖出额（万元）'),
    sa.Column('net_amount', sa.Numeric(precision=18, scale=2), nullable=True, comment='龙虎榜净买入（万元）'),
    sa.Column('close', sa.Numeric(precision=10, scale=2), nullable=True, comment='收盘价'),
    sa.Column('change_pct', sa.Numeric(precision=8, scale=4), nullable=True, comment='涨跌幅（%）'),
    sa.Column('turnover_rate', sa.Numeric(precision=8, scale=4), nullable=True, comment='换手率（%）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dragon_tiger')),
    comment='龙虎榜数据表'
    )
    op.create_index('ix_dragon_tiger_code', 'dragon_tiger', ['code'], unique=False)
    op.create_index('ix_dragon_tiger_date', 'dragon_tiger', ['trade_date'], unique=False)
    op.create_index('uq_dragon_tiger', 'dragon_tiger', ['code', 'trade_date', 'reason'], unique=True)
    op.create_table('limit_up_stocks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False, comment='股票代码'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='股票名称'),
    sa.Column('trade_date', sa.Date(), nullable=False, comment='交易日期'),
    sa.Column('limit_up_time', sa.String(length=10), nullable=True, comment='首次涨停时间（HH:MM:SS）'),
    sa.Column('open_count', sa.Integer(), nullable=False, comment='开板次数'),
    sa.Column('continuous_days', sa.Integer(), nullable=False, comment='连板天数'),
    sa.Column('industry', sa.String(length=50), nullable=True, comment='所属行业'),
    sa.Column('concept', sa.String(length=500), nullable=True, comment='涨停概念（多个用逗号分隔）'),
    sa.Column('turnover_rate', sa.Numeric(precision=8, scale=4), nullable=True, comment='换手率（%）'),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=True, comment='成交额（万元）'),
    sa.Column('seal_amount', sa.Numeric(precision=18, scale=2), nullable=True, comment='封单金额（万元）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_limit_up_stocks')),
    comment='涨停股票详情表'
    )
    op.create_index('ix_limit_up_stocks_code', 'limit_up_stocks', ['code'], unique=False)
    op.create_index('ix_limit_up_stocks_date', 'limit_up_stocks', ['trade_date'], unique=False)
    op.create_index('uq_limit_up_code_date', 'limit_up_stocks', ['code', 'trade_date'], unique=True)
    op.create_table('margin_trades',
    sa.Column('code', sa.String(length=10), nullable=False, comment='股票代码'),
    sa.Column('trade_date', sa.Date(), nullable=False, comment='交易日期'),
    sa.Column('rzye', sa.Numeric(precision=18, scale=2), nullable=True, comment='融资余额（元）'),
    sa.Column('rzmre', sa.Numeric(precision=18, scale=2), nullable=True, comment='融资买入额（元）'),
    sa.Column('rzche', sa.Numeric(precision=18, scale=2), nullable=True, comment='融资偿还额（元）'),
    sa.Column('rzjme', sa.Numeric(precision=18, scale=2), nullable=True, comment='融资净买入（元）'),
    sa.Column('rqye', sa.Numeric(precision=18, scale=2), nullable=True, comment='融券余额（元）'),
    sa.Column('rqmcl', sa.BigInteger(), nullable=True, comment='融券卖出量（股）'),
    sa.Column('rqchl', sa.BigInteger(), nullable=True, comment='融券偿还量（股）'),
    sa.Column('rzrqye', sa.Numeric(precision=18, scale=2), nullable=True, comment='融资融券余额（元）'),
    sa.PrimaryKeyConstraint('code', 'trade_date', name=op.f('pk_margin_trades')),
    comment='融资融券数据表'
    )
    op.create_index('ix_margin_trades_code', 'margin_trades', ['code'], unique=False)
    op.create_index('ix_margin_trades_date', 'margin_trades', ['trade_date'], unique=False)
    op.create_table('market_sentiments',
    sa.Column('trade_date', sa.Date(), nullable=False, comment='交易日期'),
    sa.Column('rising_count', sa.Integer(), nullable=False, comment='上涨家数'),
    sa.Column('falling_count', sa.Integer(), nullable=False, comment='下跌家数'),
    sa.Column('flat_count', sa.Integer(), nullable=False, comment='平盘家数'),
    sa.Column('limit_up_count', sa.Integer(), nullable=False, comment='涨停家数'),
    sa.Column('limit_down_count', sa.Integer(), nullable=False, comment='跌停家数'),
    sa.Column('advance_decline_ratio', sa.Numeric(precision=8, scale=4), nullable=True, comment='涨跌比（上涨/下跌）'),
    sa.Column('continuous_limit_up_count', sa.Integer(), nullable=True, comment='连板家数（2板及以上）'),
    sa.Column('max_continuous_days', sa.Integer(), nullable=True, comment='最高连板天数'),
    sa.Column('highest_board_stock', sa.String(length=10), nullable=True, comment='最高连板股票代码'),
    sa.Column('turnover_gt_10_count', sa.Integer(), nullable=True, comment='换手率>10%家数'),
    sa.Column('turnover_5_10_count', sa.Integer(), nullable=True, comment='换手率5-10%家数'),
    sa.Column('turnover_lt_1_count', sa.Integer(), nullable=True, comment='换手率<1%家数'),
    sa.Column('avg_turnover_rate', sa.Numeric(precision=8, scale=4), nullable=True, comment='全市场平均换手率（%）'),
    sa.Column('total_volume', sa.BigInteger(), nullable=True, comment='市场总成交量（手）'),
    sa.Column('total_amount', sa.Numeric(precision=20, scale=2), nullable=True, comment='市场总成交额（亿元）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('trade_date', name=op.f('pk_market_sentiments')),
    comment='市场情绪指标表'
    )
    op.create_table('northbound_flows',
    sa.Column('trade_date', sa.Date(), nullable=False, comment='交易日期'),
    sa.Column('sh_net_inflow', sa.Numeric(precision=18, scale=2), nullable=True, comment='沪股通净流入（亿元）'),
    sa.Column('sh_buy_amount', sa.Numeric(precision=18, scale=2), nullable=True, comment='沪股通买入金额（亿元）'),
    sa.Column('sh_sell_amount', sa.Numeric(precision=18, scale=2), nullable=True, comment='沪股通卖出金额（亿元）'),
    sa.Column('sz_net_inflow', sa.Numeric(precision=18, scale=2), nullable=True, comment='深股通净流入（亿元）'),
    sa.Column('sz_buy_amount', sa.Numeric(precision=18, scale=2), nullable=True, comment='深股通买入金额（亿元）'),
    sa.Column('sz_sell_amount', sa.Numeric(precision=18, scale=2), nullable=True, comment='深股通卖出金额（亿元）'),
    sa.Column('total_net_inflow', sa.Numeric(precision=18, scale=2), nullable=True, comment='北向资金净流入合计（亿元）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('trade_date', name=op.f('pk_northbound_flows')),
    comment='北向资金表'
    )
    op.create_table('stock_fund_flows',
    sa.Column('code', sa.String(length=10), nullable=False, comment='股票代码'),
    sa.Column('trade_date', sa.Date(), nullable=False, comment='交易日期'),
    sa.Column('main_net_inflow', sa.Numeric(precision=18, scale=2), nullable=True, comment='主力净流入（万元）'),
    sa.Column('main_inflow', sa.Numeric(precision=18, scale=2), nullable=True, comment='主力流入（万元）'),
    sa.Column('main_outflow', sa.Numeric(precision=18, scale=2), nullable=True, comment='主力流出（万元）'),
    sa.Column('super_large_net', sa.Numeric(precision=18, scale=2), nullable=True, comment='超大单净流入（万元）'),
    sa.Column('large_net', sa.Numeric(precision=18, scale=2), nullable=True, comment='大单净流入（万元）'),
    sa.Column('medium_net', sa.Numeric(precision=18, scale=2), nullable=True, comment='中单净流入（万元）'),
    sa.Column('small_net', sa.Numeric(precision=18, scale=2), nullable=True, comment='小单净流入（万元）'),
    sa.Column('main_net_pct', sa.Numeric(precision=8, scale=4), nullable=True, comment='主力净占比（%）'),
    sa.PrimaryKeyConstraint('code', 'trade_date', name=op.f('pk_stock_fund_flows')),
    comment='个股主力资金流向表'
    )
    op.create_index('ix_stock_fund_flows_code', 'stock_fund_flows', ['code'], unique=False)
    op.create_index('ix_stock_fund_flows_date', 'stock_fund_flows', ['trade_date'], unique=False)
    op.create_table('tech_indicators',
    sa.Column('code', sa.String(length=10), nullable=False, comment='股票代码'),
    sa.Column('trade_date', sa.Date(), nullable=False, comment='交易日期'),
    sa.Column('ma5', sa.Numeric(precision=10, scale=2), nullable=True, comment='5日均线'),
    sa.Column('ma10', sa.Numeric(precision=10, scale=2), nullable=True, comment='10日均线'),
    sa.Column('ma20', sa.Numeric(precision=10, scale=2), nullable=True, comment='20日均线'),
    sa.Column('ma60', sa.Numeric(precision=10, scale=2), nullable=True, comment='60日均线'),
    sa.Column('macd_dif', sa.Numeric(precision=10, scale=4), nullable=True, comment='MACD DIF'),
    sa.Column('macd_dea', sa.Numeric(precision=10, scale=4), nullable=True, comment='MACD DEA'),
    sa.Column('macd_bar', sa.Numeric(precision=10, scale=4), nullable=True, comment='MACD Bar (柱状)'),
    sa.Column('rsi_14', sa.Numeric(precision=8, scale=4), nullable=True, comment='14日RSI'),
    sa.Column('kdj_k', sa.Numeric(precision=8, scale=4), nullable=True, comment='KDJ K值'),
    sa.Column('kdj_d', sa.Numeric(precision=8, scale=4), nullable=True, comment='KDJ D值'),
    sa.Column('kdj_j', sa.Numeric(precision=8, scale=4), nullable=True, comment='KDJ J值'),
    sa.Column('boll_upper', sa.Numeric(precision=10, scale=2), nullable=True, comment='布林带上轨'),
    sa.Column('boll_middle', sa.Numeric(precision=10, scale=2), nullable=True, comment='布林带中轨'),
    sa.Column('boll_lower', sa.Numeric(precision=10, scale=2), nullable=True, comment='布林带下轨'),
    sa.Column('cci', sa.Numeric(precision=10, scale=4), nullable=True, comment='CCI指标'),
    sa.Column('atr_14', sa.Numeric(precision=10, scale=4), nullable=True, comment='14日ATR'),
    sa.Column('obv', sa.BigInteger(), nullable=True, comment='OBV（累积成交量）'),
    sa.PrimaryKeyConstraint('code', 'trade_date', name=op.f('pk_tech_indicators')),
    comment='技术指标预计算表'
    )
    op.create_index('ix_tech_indicators_code', 'tech_indicators', ['code'], unique=False)
    op.create_index('ix_tech_indicators_date', 'tech_indicators', ['trade_date'], unique=False)
    op.create_index('ix_tech_indicators_macd', 'tech_indicators', ['trade_date', 'macd_bar'], unique=False)
    op.create_index('ix_tech_indicators_rsi', 'tech_indicators', ['trade_date', 'rsi_14'], unique=False)
    op.alter_column('daily_quotes', 'volume',
               existing_type=sa.BIGINT(),
               comment='成交量 (股)',
               existing_comment='成交量',
               existing_nullable=True)
    op.alter_column('daily_quotes', 'amount',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               comment='成交额 (元)',
               existing_comment='成交额',
               existing_nullable=True)
    op.alter_column('daily_quotes', 'change_pct',
               existing_type=sa.NUMERIC(precision=8, scale=4),
               comment='涨跌幅 (%)',
               existing_comment='涨跌幅',
               existing_nullable=True)
    op.alter_column('daily_quotes', 'turnover_rate',
               existing_type=sa.NUMERIC(precision=8, scale=4),
               comment='换手率 (%)',
               existing_comment='换手率',
               existing_nullable=True)
    op.create_table_comment(
        'daily_quotes',
        '日线行情表 (TimescaleDB Hypertable)',
        existing_comment='日线行情表',
        schema=None
    )
    op.alter_column('macro_indicators', 'indicator_name',
               existing_type=sa.VARCHAR(length=50),
               comment='指标名称: GDP, CPI, PPI, PMI, M2, 社融, 外汇储备等',
               existing_comment='指标名称: GDP, CPI, PPI, PMI, M2等',
               existing_nullable=False)
    op.alter_column('macro_indicators', 'indicator_category',
               existing_type=sa.VARCHAR(length=50),
               comment='指标分类: 国民经济, 价格指数, 货币供应, 对外经济等',
               existing_comment='指标分类: 国民经济, 价格指数, 货币供应等',
               existing_nullable=False)
    op.alter_column('macro_indicators', 'period',
               existing_type=sa.DATE(),
               comment='统计周期（月度/季度）',
               existing_comment='统计周期',
               existing_nullable=False)
    op.alter_column('macro_indicators', 'yoy_rate',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               comment='同比增长率 (%)',
               existing_comment='同比增长率(%)',
               existing_nullable=True)
    op.alter_column('macro_indicators', 'mom_rate',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               comment='环比增长率 (%)',
               existing_comment='环比增长率(%)',
               existing_nullable=True)
    op.alter_column('macro_indicators', 'unit',
               existing_type=sa.VARCHAR(length=50),
               comment='数据单位: 亿元, 百分点, 点等',
               existing_comment='数据单位',
               existing_nullable=True)
    op.alter_column('minute_quotes', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_comment='时间戳',
               existing_nullable=False)
    op.drop_index(op.f('minute_quotes_timestamp_idx'), table_name='minute_quotes')
    op.create_table_comment(
        'minute_quotes',
        '分钟行情表 (TimescaleDB Hypertable)',
        existing_comment='分钟行情表',
        schema=None
    )
    op.alter_column('news_articles', 'source',
               existing_type=sa.VARCHAR(length=50),
               comment='数据源: eastmoney-东方财富, sina-新浪财经, etc.',
               existing_comment='数据源: eastmoney/sina/etc.',
               existing_nullable=False)
    op.alter_column('sector_quotes', 'change_pct',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               comment='涨跌幅 (%)',
               existing_comment='涨跌幅(%)',
               existing_nullable=True)
    op.alter_column('sector_quotes', 'total_volume',
               existing_type=sa.INTEGER(),
               comment='总成交量（手）',
               existing_comment='总成交量(手)',
               existing_nullable=True)
    op.alter_column('sector_quotes', 'total_amount',
               existing_type=sa.NUMERIC(precision=20, scale=2),
               comment='总成交额（元）',
               existing_comment='总成交额(元)',
               existing_nullable=True)
    op.alter_column('sector_quotes', 'leading_stock_pct',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               comment='领涨股涨跌幅 (%)',
               existing_comment='领涨股涨跌幅(%)',
               existing_nullable=True)
    op.alter_column('sectors', 'sector_type',
               existing_type=sa.VARCHAR(length=20),
               comment='板块类型: industry-行业, concept-概念, region-地域',
               existing_comment='板块类型: industry/concept/region',
               existing_nullable=False)
    op.alter_column('sectors', 'level',
               existing_type=sa.INTEGER(),
               comment='板块级别: 1-一级行业, 2-二级行业, 3-三级行业',
               existing_comment='板块级别',
               existing_nullable=True)
    op.alter_column('sectors', 'parent_code',
               existing_type=sa.VARCHAR(length=20),
               comment='父板块代码（用于多级行业分类）',
               existing_comment='父板块代码',
               existing_nullable=True)
    op.alter_column('stocks', 'code',
               existing_type=sa.VARCHAR(length=10),
               comment='股票代码，如 000001, 600519',
               existing_comment='股票代码',
               existing_nullable=False)
    op.alter_column('stocks', 'market',
               existing_type=sa.VARCHAR(length=10),
               comment='市场: SH-上海, SZ-深圳, BJ-北京',
               existing_comment='市场: SH/SZ/BJ',
               existing_nullable=False)
    op.alter_column('stocks', 'asset_type',
               existing_type=sa.VARCHAR(length=10),
               comment='类型: stock-股票, etf-ETF',
               existing_comment='类型: stock/etf',
               existing_nullable=False,
               existing_server_default=sa.text("'stock'::character varying"))
    op.alter_column('stocks', 'industry',
               existing_type=sa.VARCHAR(length=50),
               comment='所属行业',
               existing_comment='行业',
               existing_nullable=True)
    op.alter_column('watchlist', 'sort_order',
               existing_type=sa.INTEGER(),
               comment='排序顺序',
               existing_comment='排序',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('watchlist', 'sort_order',
               existing_type=sa.INTEGER(),
               comment='排序',
               existing_comment='排序顺序',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('stocks', 'industry',
               existing_type=sa.VARCHAR(length=50),
               comment='行业',
               existing_comment='所属行业',
               existing_nullable=True)
    op.alter_column('stocks', 'asset_type',
               existing_type=sa.VARCHAR(length=10),
               comment='类型: stock/etf',
               existing_comment='类型: stock-股票, etf-ETF',
               existing_nullable=False,
               existing_server_default=sa.text("'stock'::character varying"))
    op.alter_column('stocks', 'market',
               existing_type=sa.VARCHAR(length=10),
               comment='市场: SH/SZ/BJ',
               existing_comment='市场: SH-上海, SZ-深圳, BJ-北京',
               existing_nullable=False)
    op.alter_column('stocks', 'code',
               existing_type=sa.VARCHAR(length=10),
               comment='股票代码',
               existing_comment='股票代码，如 000001, 600519',
               existing_nullable=False)
    op.alter_column('sectors', 'parent_code',
               existing_type=sa.VARCHAR(length=20),
               comment='父板块代码',
               existing_comment='父板块代码（用于多级行业分类）',
               existing_nullable=True)
    op.alter_column('sectors', 'level',
               existing_type=sa.INTEGER(),
               comment='板块级别',
               existing_comment='板块级别: 1-一级行业, 2-二级行业, 3-三级行业',
               existing_nullable=True)
    op.alter_column('sectors', 'sector_type',
               existing_type=sa.VARCHAR(length=20),
               comment='板块类型: industry/concept/region',
               existing_comment='板块类型: industry-行业, concept-概念, region-地域',
               existing_nullable=False)
    op.alter_column('sector_quotes', 'leading_stock_pct',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               comment='领涨股涨跌幅(%)',
               existing_comment='领涨股涨跌幅 (%)',
               existing_nullable=True)
    op.alter_column('sector_quotes', 'total_amount',
               existing_type=sa.NUMERIC(precision=20, scale=2),
               comment='总成交额(元)',
               existing_comment='总成交额（元）',
               existing_nullable=True)
    op.alter_column('sector_quotes', 'total_volume',
               existing_type=sa.INTEGER(),
               comment='总成交量(手)',
               existing_comment='总成交量（手）',
               existing_nullable=True)
    op.alter_column('sector_quotes', 'change_pct',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               comment='涨跌幅(%)',
               existing_comment='涨跌幅 (%)',
               existing_nullable=True)
    op.alter_column('news_articles', 'source',
               existing_type=sa.VARCHAR(length=50),
               comment='数据源: eastmoney/sina/etc.',
               existing_comment='数据源: eastmoney-东方财富, sina-新浪财经, etc.',
               existing_nullable=False)
    op.create_table_comment(
        'minute_quotes',
        '分钟行情表',
        existing_comment='分钟行情表 (TimescaleDB Hypertable)',
        schema=None
    )
    op.create_index(op.f('minute_quotes_timestamp_idx'), 'minute_quotes', [sa.literal_column('timestamp DESC')], unique=False)
    op.alter_column('minute_quotes', 'timestamp',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_comment='时间戳',
               existing_nullable=False)
    op.alter_column('macro_indicators', 'unit',
               existing_type=sa.VARCHAR(length=50),
               comment='数据单位',
               existing_comment='数据单位: 亿元, 百分点, 点等',
               existing_nullable=True)
    op.alter_column('macro_indicators', 'mom_rate',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               comment='环比增长率(%)',
               existing_comment='环比增长率 (%)',
               existing_nullable=True)
    op.alter_column('macro_indicators', 'yoy_rate',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               comment='同比增长率(%)',
               existing_comment='同比增长率 (%)',
               existing_nullable=True)
    op.alter_column('macro_indicators', 'period',
               existing_type=sa.DATE(),
               comment='统计周期',
               existing_comment='统计周期（月度/季度）',
               existing_nullable=False)
    op.alter_column('macro_indicators', 'indicator_category',
               existing_type=sa.VARCHAR(length=50),
               comment='指标分类: 国民经济, 价格指数, 货币供应等',
               existing_comment='指标分类: 国民经济, 价格指数, 货币供应, 对外经济等',
               existing_nullable=False)
    op.alter_column('macro_indicators', 'indicator_name',
               existing_type=sa.VARCHAR(length=50),
               comment='指标名称: GDP, CPI, PPI, PMI, M2等',
               existing_comment='指标名称: GDP, CPI, PPI, PMI, M2, 社融, 外汇储备等',
               existing_nullable=False)
    op.create_table_comment(
        'daily_quotes',
        '日线行情表',
        existing_comment='日线行情表 (TimescaleDB Hypertable)',
        schema=None
    )
    op.alter_column('daily_quotes', 'turnover_rate',
               existing_type=sa.NUMERIC(precision=8, scale=4),
               comment='换手率',
               existing_comment='换手率 (%)',
               existing_nullable=True)
    op.alter_column('daily_quotes', 'change_pct',
               existing_type=sa.NUMERIC(precision=8, scale=4),
               comment='涨跌幅',
               existing_comment='涨跌幅 (%)',
               existing_nullable=True)
    op.alter_column('daily_quotes', 'amount',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               comment='成交额',
               existing_comment='成交额 (元)',
               existing_nullable=True)
    op.alter_column('daily_quotes', 'volume',
               existing_type=sa.BIGINT(),
               comment='成交量',
               existing_comment='成交量 (股)',
               existing_nullable=True)
    op.drop_index('ix_tech_indicators_rsi', table_name='tech_indicators')
    op.drop_index('ix_tech_indicators_macd', table_name='tech_indicators')
    op.drop_index('ix_tech_indicators_date', table_name='tech_indicators')
    op.drop_index('ix_tech_indicators_code', table_name='tech_indicators')
    op.drop_table('tech_indicators')
    op.drop_index('ix_stock_fund_flows_date', table_name='stock_fund_flows')
    op.drop_index('ix_stock_fund_flows_code', table_name='stock_fund_flows')
    op.drop_table('stock_fund_flows')
    op.drop_table('northbound_flows')
    op.drop_table('market_sentiments')
    op.drop_index('ix_margin_trades_date', table_name='margin_trades')
    op.drop_index('ix_margin_trades_code', table_name='margin_trades')
    op.drop_table('margin_trades')
    op.drop_index('uq_limit_up_code_date', table_name='limit_up_stocks')
    op.drop_index('ix_limit_up_stocks_date', table_name='limit_up_stocks')
    op.drop_index('ix_limit_up_stocks_code', table_name='limit_up_stocks')
    op.drop_table('limit_up_stocks')
    op.drop_index('uq_dragon_tiger', table_name='dragon_tiger')
    op.drop_index('ix_dragon_tiger_date', table_name='dragon_tiger')
    op.drop_index('ix_dragon_tiger_code', table_name='dragon_tiger')
    op.drop_table('dragon_tiger')
    op.drop_index('ix_daily_valuations_date', table_name='daily_valuations')
    op.drop_index('ix_daily_valuations_code', table_name='daily_valuations')
    op.drop_table('daily_valuations')
    # ### end Alembic commands ###
