"""add sync_errors table for error tracking

Revision ID: 9ea5074f1d61
Revises: ebb24035e7c2
Create Date: 2025-12-26 14:42:29.407206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ea5074f1d61'
down_revision: Union[str, None] = 'ebb24035e7c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'sync_errors',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('task_name', sa.String(length=100), nullable=False),
        sa.Column('target_code', sa.String(length=20), nullable=False),
        sa.Column('error_type', sa.String(length=50), nullable=False),
        sa.Column('error_message', sa.Text(), nullable=False),
        sa.Column('retry_count', sa.Integer(), nullable=True),
        sa.Column('last_retry_at', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('resolved_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sync_errors_created', 'sync_errors', ['created_at'], unique=False)
    op.create_index('ix_sync_errors_task_code', 'sync_errors', ['task_name', 'target_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sync_errors_task_code', table_name='sync_errors')
    op.drop_index('ix_sync_errors_created', table_name='sync_errors')
    op.drop_table('sync_errors')
    # ### end Alembic commands ###
