"""add operation_data table

Revision ID: ebb24035e7c2
Revises: 03af93834e28
Create Date: 2025-12-26 07:23:33.966870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebb24035e7c2'
down_revision: Union[str, None] = '03af93834e28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operation_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False, comment='股票代码'),
    sa.Column('period', sa.String(length=20), nullable=False, comment='报告期（YYYY-MM-DD 或 YYYYQN）'),
    sa.Column('metric_name', sa.String(length=100), nullable=False, comment='指标名称（如：销量、市场份额、产能利用率等）'),
    sa.Column('metric_category', sa.String(length=50), nullable=True, comment='指标分类（如：产销、订单、市场等）'),
    sa.Column('metric_value', sa.Numeric(precision=20, scale=4), nullable=True, comment='指标数值'),
    sa.Column('metric_value_text', sa.String(length=500), nullable=True, comment='指标文本值（用于非数值型数据）'),
    sa.Column('unit', sa.String(length=50), nullable=True, comment='单位（如：万台、%、万吨等）'),
    sa.Column('source', sa.String(length=200), nullable=True, comment='数据来源（如：公司公告、行业报告等）'),
    sa.Column('remark', sa.String(length=500), nullable=True, comment='备注信息'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_operation_data')),
    comment='经营数据表（KV结构）'
    )
    op.create_index('ix_operation_data_code', 'operation_data', ['code'], unique=False)
    op.create_index('ix_operation_data_metric', 'operation_data', ['metric_name'], unique=False)
    op.create_index('ix_operation_data_period', 'operation_data', ['period'], unique=False)
    op.create_index('uq_operation_data', 'operation_data', ['code', 'period', 'metric_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_operation_data', table_name='operation_data')
    op.drop_index('ix_operation_data_period', table_name='operation_data')
    op.drop_index('ix_operation_data_metric', table_name='operation_data')
    op.drop_index('ix_operation_data_code', table_name='operation_data')
    op.drop_table('operation_data')
    # ### end Alembic commands ###
